---
- name: Download apt repository list
  get_url:
    url: "{{ ambari_server_repo_download_url }}"
    dest: /etc/apt/sources.list.d/ambari.list

- name: Add apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ ambari_server_apt_key }}"
    state: present